### ISSUE TITLE
Maestro yaml file configures workspace repositories

### ISSUE THREAD

**Issue by eighty4** [eighty4/maestro#1]
Maestro should read a yaml config file from the program's cwd on startup and include any repo records at `$.workspace.repositories` with the call to `git.NewWorkspace`. `Workspace.Sync` should `git clone` repositories that are not present within the workspace or do a `git pull` for already cloned projects.

Repositories can be configured with their name, path and git url. Path must be an ancestor path of the program's cwd (`../foo` is not permitted).

```yaml
workspace:
  repositories:
    - name: fomo
      path: fomo
      git:
        url: git@github.com:eighty4/fomo
    - name: picking
      path: picking
      git:
        url: git@github.com:eighty4/picking
```

Only git url is required. Name and path are optional and will use the default behavior of git clone, using the repository name for an omitted name or path. In this example the repository would be named `fomo` and would be cloned into `./fomo`:

```yaml
workspace:
  repositories:
    - git:
        url: git@github.com:eighty4/fomo
```

A repository's path can be any nested directory structure within the program's cwd. In this scenario, an omitted name will default to the path value. These repositories in this example will have names `plaid/trousers` and `plaid/banking`:

```yaml
workspace:
  repositories:
    - path: plaid/trousers
      git:
        url: git@github.com:eighty4/trousers
    - path: plaid/banking
      git:
        url: git@github.com:eighty4/banking
```
